# Handling Missing Data

The Data Science Process
1. Buisiness discussion
2. Data discussion
3. Data preparation
4. Modeling
5. Evaluation
6. Deployment

## Data Preparation
1. Cleaning the Data
    - Missing Data <--- Today
    - Cleaning Labels
    - Formats of variables
2. Data Wrangling
    - Encoding categorical data
    - Rearranging data
    - Combining datasets

## Missing Data
How is missing data represented?
- Null or Empty
- 0
- -1 or -9999 or 9999 {a ridiculous number that can't be true}
- Characters ("---", "N/A")
- NaN  
If we have missing values, what do we do with them?
- Drop
    - We can drop columns if data is missing for the majority of observations
    - We can drop rows if the missing data interfers with the model and if the other data isn't crucial
    - When to drop?
        - When the present data that would be dropped isn't crucial to the model
- Fill in missing values with an estimate (imputing)
    - Use a Linear Regression to estimate
    - Compare to other variables
    - Fill with average values
    - Interpolate (Good when values follow a sequence)
        - Average of surrounding vlaues
        - Forward Fill: A missing value takes on the previous value
        - Back FIll: A missing value takes on the next value

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
display(titanic)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
titanic.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [5]:
filter = (titanic['embarked'].isna())
titanic[filter]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
61,1,1,female,38.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True
829,1,1,female,62.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True

In [7]:
titanic.shape

(891, 15)

In [8]:
titanic.drop(['embarked', 'deck'], axis=1, inplace=True)

In [9]:
titanic.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
class            0
who              0
adult_male       0
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
titanic_filtered = titanic.drop([61,829], axis=0)
titanic_filtered[titanic_filtered['embark_town'].isna()]
titanic_filtered.loc[61]

Empty DataFrame
Columns: [survived, pclass, sex, age, sibsp, parch, fare, class, who, adult_male, embark_town, alive, alone]
Index: []

In [11]:
titanic.dropna(subset='embark_town', inplace=True)

When do I drop data?
- If more than half of a variable is missing, drop the variable
- If less than 10% of a variable is missing, drop the observations

Exact numbers up to Data Scientist's discretion  
Don't drop if the other information is still valuable

## Imputing Data

In [14]:
display(titanic['age'].to_numpy())

array([22.  , 38.  , 26.  , 35.  , 35.  ,   nan, 54.  ,  2.  , 27.  ,
       14.  ,  4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  ,   nan,
       31.  ,   nan, 35.  , 34.  , 15.  , 28.  ,  8.  , 38.  ,   nan,
       19.  ,   nan,   nan, 40.  ,   nan,   nan, 66.  , 28.  , 42.  ,
         nan, 21.  , 18.  , 14.  , 40.  , 27.  ,   nan,  3.  , 19.  ,
         nan,   nan,   nan,   nan, 18.  ,  7.  , 21.  , 49.  , 29.  ,
       65.  ,   nan, 21.  , 28.5 ,  5.  , 11.  , 22.  , 45.  ,  4.  ,
         nan,   nan, 29.  , 19.  , 17.  , 26.  , 32.  , 16.  , 21.  ,
       26.  , 32.  , 25.  ,   nan,   nan,  0.83, 30.  , 22.  , 29.  ,
         nan, 28.  , 17.  , 33.  , 16.  ,   nan, 23.  , 24.  , 29.  ,
       20.  , 46.  , 26.  , 59.  ,   nan, 71.  , 23.  , 34.  , 34.  ,
       28.  ,   nan, 21.  , 33.  , 37.  , 28.  , 21.  ,   nan, 38.  ,
         nan, 47.  , 14.5 , 22.  , 20.  , 17.  , 21.  , 70.5 , 29.  ,
       24.  ,  2.  , 21.  ,   nan, 32.5 , 32.5 , 54.  , 12.  ,   nan,
       24.  ,   nan, 45.  , 33.  , 20.  , 47.  , 29.  , 25.  , 23.  ,
       19.  , 37.  , 16.  , 24.  ,   nan, 22.  , 24.  , 19.  , 18.  ,
       19.  , 27.  ,  9.  , 36.5 , 42.  , 51.  , 22.  , 55.5 , 40.5 ,
         nan, 51.  , 16.  , 30.  ,   nan,   nan, 44.  , 40.  , 26.  ,
       17.  ,  1.  ,  9.  ,   nan, 45.  ,   nan, 28.  , 61.  ,  4.  ,
        1.  , 21.  , 56.  , 18.  ,   nan, 50.  , 30.  , 36.  ,   nan,
         nan,  9.  ,  1.  ,  4.  ,   nan,   nan, 45.  , 40.  , 36.  ,
       32.  , 19.  , 19.  ,  3.  , 44.  , 58.  ,   nan, 42.  ,   nan,
       24.  , 28.  ,   nan, 34.  , 45.5 , 18.  ,  2.  , 32.  , 26.  ,
       16.  , 40.  , 24.  , 35.  , 22.  , 30.  ,   nan, 31.  , 27.  ,
       42.  , 32.  , 30.  , 16.  , 27.  , 51.  ,   nan, 38.  , 22.  ,
       19.  , 20.5 , 18.  ,   nan, 35.  , 29.  , 59.  ,  5.  , 24.  ,
         nan, 44.  ,  8.  , 19.  , 33.  ,   nan,   nan, 29.  , 22.  ,
       30.  , 44.  , 25.  , 24.  , 37.  , 54.  ,   nan, 29.  , 62.  ,
       30.  , 41.  , 29.  ,   nan, 30.  , 35.  , 50.  ,   nan,  3.  ,
       52.  , 40.  ,   nan, 36.  , 16.  , 25.  , 58.  , 35.  ,   nan,
       25.  , 41.  , 37.  ,   nan, 63.  , 45.  ,   nan,  7.  , 35.  ,
       65.  , 28.  , 16.  , 19.  ,   nan, 33.  , 30.  , 22.  , 42.  ,
       22.  , 26.  , 19.  , 36.  , 24.  , 24.  ,   nan, 23.5 ,  2.  ,
         nan, 50.  ,   nan,   nan, 19.  ,   nan,   nan,  0.92,   nan,
       17.  , 30.  , 30.  , 24.  , 18.  , 26.  , 28.  , 43.  , 26.  ,
       24.  , 54.  , 31.  , 40.  , 22.  , 27.  , 30.  , 22.  ,   nan,
       36.  , 61.  , 36.  , 31.  , 16.  ,   nan, 45.5 , 38.  , 16.  ,
         nan,   nan, 29.  , 41.  , 45.  , 45.  ,  2.  , 24.  , 28.  ,
       25.  , 36.  , 24.  , 40.  ,   nan,  3.  , 42.  , 23.  ,   nan,
       15.  , 25.  ,   nan, 28.  , 22.  , 38.  ,   nan,   nan, 40.  ,
       29.  , 45.  , 35.  ,   nan, 30.  , 60.  ,   nan,   nan, 24.  ,
       25.  , 18.  , 19.  , 22.  ,  3.  ,   nan, 22.  , 27.  , 20.  ,
       19.  , 42.  ,  1.  , 32.  , 35.  ,   nan, 18.  ,  1.  , 36.  ,
         nan, 17.  , 36.  , 21.  , 28.  , 23.  , 24.  , 22.  , 31.  ,
       46.  , 23.  , 28.  , 39.  , 26.  , 21.  , 28.  , 20.  , 34.  ,
       51.  ,  3.  , 21.  ,   nan,   nan,   nan, 33.  ,   nan, 44.  ,
         nan, 34.  , 18.  , 30.  , 10.  ,   nan, 21.  , 29.  , 28.  ,
       18.  ,   nan, 28.  , 19.  ,   nan, 32.  , 28.  ,   nan, 42.  ,
       17.  , 50.  , 14.  , 21.  , 24.  , 64.  , 31.  , 45.  , 20.  ,
       25.  , 28.  ,   nan,  4.  , 13.  , 34.  ,  5.  , 52.  , 36.  ,
         nan, 30.  , 49.  ,   nan, 29.  , 65.  ,   nan, 50.  ,   nan,
       48.  , 34.  , 47.  , 48.  ,   nan, 38.  ,   nan, 56.  ,   nan,
        0.75,   nan, 38.  , 33.  , 23.  , 22.  ,   nan, 34.  , 29.  ,
       22.  ,  2.  ,  9.  ,   nan, 50.  , 63.  , 25.  ,   nan, 35.  ,
       58.  , 30.  ,  9.  ,   nan, 21.  , 55.  , 71.  , 21.  ,   nan,
       54.  ,   nan, 25.  , 24.  , 17.  , 21.  ,   nan, 37.  , 16.  ,
       18.  , 33.  ,   nan, 28.  , 26.  , 29.  ,   nan, 36.  , 54.  ,
       24.  , 47.  , 34.  ,   nan, 36.  , 32.  , 30.  , 22.  ,   nan,
       44.  ,   nan, 40.5 , 50.  ,   nan, 39.  , 23.  ,  2.  ,   nan,
       17.  ,   nan, 30.  ,  7.  , 45.  , 30.  ,   nan, 22.  , 36.  ,
        9.  , 11.  , 32.  , 50.  , 64.  , 19.  ,   nan, 33.  ,  8.  ,
       17.  , 27.  ,   nan, 22.  , 22.  , 62.  , 48.  ,   nan, 39.  ,
       36.  ,   nan, 40.  , 28.  ,   nan,   nan, 24.  , 19.  , 29.  ,
         nan, 32.  , 62.  , 53.  , 36.  ,   nan, 16.  , 19.  , 34.  ,
       39.  ,   nan, 32.  , 25.  , 39.  , 54.  , 36.  ,   nan, 18.  ,
       47.  , 60.  , 22.  ,   nan, 35.  , 52.  , 47.  ,   nan, 37.  ,
       36.  ,   nan, 49.  ,   nan, 49.  , 24.  ,   nan,   nan, 44.  ,
       35.  , 36.  , 30.  , 27.  , 22.  , 40.  , 39.  ,   nan,   nan,
         nan, 35.  , 24.  , 34.  , 26.  ,  4.  , 26.  , 27.  , 42.  ,
       20.  , 21.  , 21.  , 61.  , 57.  , 21.  , 26.  ,   nan, 80.  ,
       51.  , 32.  ,   nan,  9.  , 28.  , 32.  , 31.  , 41.  ,   nan,
       20.  , 24.  ,  2.  ,   nan,  0.75, 48.  , 19.  , 56.  ,   nan,
       23.  ,   nan, 18.  , 21.  ,   nan, 18.  , 24.  ,   nan, 32.  ,
       23.  , 58.  , 50.  , 40.  , 47.  , 36.  , 20.  , 32.  , 25.  ,
         nan, 43.  ,   nan, 40.  , 31.  , 70.  , 31.  ,   nan, 18.  ,
       24.5 , 18.  , 43.  , 36.  ,   nan, 27.  , 20.  , 14.  , 60.  ,
       25.  , 14.  , 19.  , 18.  , 15.  , 31.  ,  4.  ,   nan, 25.  ,
       60.  , 52.  , 44.  ,   nan, 49.  , 42.  , 18.  , 35.  , 18.  ,
       25.  , 26.  , 39.  , 45.  , 42.  , 22.  ,   nan, 24.  ,   nan,
       48.  , 29.  , 52.  , 19.  , 38.  , 27.  ,   nan, 33.  ,  6.  ,
       17.  , 34.  , 50.  , 27.  , 20.  , 30.  ,   nan, 25.  , 25.  ,
       29.  , 11.  ,   nan, 23.  , 23.  , 28.5 , 48.  , 35.  ,   nan,
         nan,   nan, 36.  , 21.  , 24.  , 31.  , 70.  , 16.  , 30.  ,
       19.  , 31.  ,  4.  ,  6.  , 33.  , 23.  , 48.  ,  0.67, 28.  ,
       18.  , 34.  , 33.  ,   nan, 41.  , 20.  , 36.  , 16.  , 51.  ,
         nan, 30.5 ,   nan, 32.  , 24.  , 48.  , 57.  ,   nan, 54.  ,
       18.  ,   nan,  5.  ,   nan, 43.  , 13.  , 17.  , 29.  ,   nan,
       25.  , 25.  , 18.  ,  8.  ,  1.  , 46.  ,   nan, 16.  ,   nan,
         nan, 25.  , 39.  , 49.  , 31.  , 30.  , 30.  , 34.  , 31.  ,
       11.  ,  0.42, 27.  , 31.  , 39.  , 18.  , 39.  , 33.  , 26.  ,
       39.  , 35.  ,  6.  , 30.5 ,   nan, 23.  , 31.  , 43.  , 10.  ,
       52.  , 27.  , 38.  , 27.  ,  2.  ,   nan,   nan,  1.  ,   nan,
       15.  ,  0.83,   nan, 23.  , 18.  , 39.  , 21.  ,   nan, 32.  ,
         nan, 20.  , 16.  , 30.  , 34.5 , 17.  , 42.  ,   nan, 35.  ,
       28.  ,   nan,  4.  , 74.  ,  9.  , 16.  , 44.  , 18.  , 45.  ,
       51.  , 24.  ,   nan, 41.  , 21.  , 48.  ,   nan, 24.  , 42.  ,
       27.  , 31.  ,   nan,  4.  , 26.  , 47.  , 33.  , 47.  , 28.  ,
       15.  , 20.  , 19.  ,   nan, 56.  , 25.  , 33.  , 22.  , 28.  ,
       25.  , 39.  , 27.  , 19.  ,   nan, 26.  , 32.  ])

In [ ]:
titanic['age'].fillna(titanic['age'].mean())

In [15]:
titanic_alt = titanic.replace(np.nan, 9999)

In [17]:
display(titanic_alt)

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,Second,man,True,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,First,woman,False,Southampton,yes,True
888,0,3,female,9999.0,1,2,23.4500,Third,woman,False,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,First,man,True,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Third,man,True,Queenstown,no,True

In [18]:
titanic_alt.replace(9999, np.nan)

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,Second,man,True,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,First,woman,False,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,Third,woman,False,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,First,man,True,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Third,man,True,Queenstown,no,True